<a href="https://colab.research.google.com/github/forbiddenscholar/ArtExtract/blob/main/ArtExtract_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
objects = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/objects.csv')
published_images = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/published_images.csv')

/tmp/ipykernel_233/896123519.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  objects = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/objects.csv')

In [3]:
objects

,objectid,uuid,accessioned,accessionnum,locationid,title,displaydate,beginyear,endyear,visualbrowsertimespan,...,parentid,isvirtual,departmentabbr,portfolio,series,volume,watermarks,lastdetectedmodification,wikidataid,customprinturl
0,0,b5dc500c-be86-4b05-93fa-59a25d8775fb,1,1937.1.2.c,NaN,Saint James Major,c. 1310,1310.0,1310.0,1300 to 1400,...,34.0,0,CIS-R,NaN,NaN,NaN,NaN,2023-05-09 17:01:03.48-04,Q20172973,NaN
1,1,59e0e07c-208e-4d24-a3d3-f4a56d20d6d3,1,1937.1.3,NaN,Saint Paul and a Group of Worshippers,1333,1333.0,1333.0,1300 to 1400,...,NaN,0,CIS-R,NaN,NaN,NaN,NaN,2024-02-12 16:33:23.167-05,Q20173083,NaN
2,2,95cfbfd3-5947-4834-b1cf-bf92ee1a7340,1,1937.1.4.a,8198.0,Saint Andrew and Saint Benedict with the Archa...,shortly before 1387,1387.0,1387.0,1300 to 1400,...,206122.0,0,CIS-R,NaN,NaN,NaN,NaN,2024-03-08 14:32:09.57-05,Q20173290,NaN
3,3,3277a6d0-d92e-4684-9d86-2be2cbe3c5f2,1,1937.1.4.b,8198.0,Madonna and Child Enthroned with Twelve Angels...,shortly before 1387,1387.0,1387.0,1300 to 1400,...,206122.0,0,CIS-R,NaN,NaN,NaN,NaN,2024-03-08 14:32:09.57-05,Q20173280,NaN
4,4,63225dec-d421-4ece-9f2a-335dd2dfeea1,1,1937.1.4.c,8198.0,Saint Bernard and Saint Catherine of Alexandri...,shortly before 1387,1387.0,1387.0,1300 to 1400,...,206122.0,0,CIS-R,NaN,NaN,NaN,NaN,2024-03-08 14:32:09.57-05,Q20173299,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144187,232396,85d83d4b-477b-4f99-89a4-bc184fdf4d37,1,2025.100.141,NaN,Portrait of a Man,c. 1931,1926.0,1936.0,1926 to 1950,...,NaN,0,CPH,NaN,NaN,NaN,NaN,2026-02-13 22:01:41.52-05,NaN,NaN
144188,232405,40b10576-6067-4cd8-bc4f-f524deda4128,1,2025.93.1,NaN,Hagar I,1948,1948.0,1948.0,1926 to 1950,...,NaN,0,CMC,NaN,NaN,NaN,NaN,2026-02-27 22:01:38.93-05,NaN,NaN
144189,232408,01e3a928-f505-405e-888f-9f8949f5098a,1,2025.92.1,NaN,Tabula,1973,1973.0,1973.0,1951 to 1975,...,NaN,0,CMC,NaN,NaN,NaN,NaN,2026-02-09 20:22:24.733-05,NaN,NaN
144190,233932,01e21be8-2ef9-4f30-9580-e6b99b867327,1,2025.101.2.1-50,NaN,Genesis,2005,2005.0,2005.0,2001 to present,...,NaN,0,CPH,Genesis,NaN,NaN,NaN,2026-02-20 22:01:39.217-05,NaN,NaN
144191,233967,29ceab01-0cc3-4df8-81df-8eaa02478695,1,2025.98.1-69,NaN,The Family,"May 5, 1976",1976.0,1976.0,1976 to 2000,...,NaN,0,CPH,The Family,NaN,NaN,NaN,2026-03-04 22:01:40.283-05,NaN,NaN

In [4]:
published_images

,uuid,iiifurl,iiifthumburl,viewtype,sequence,width,height,maxpixels,openaccess,created,modified,depictstmsobjectid,assistivetext
0,00007f61-4922-417b-8f27-893ea328206c,https://api.nga.gov/iiif/00007f61-4922-417b-8f...,https://api.nga.gov/iiif/00007f61-4922-417b-8f...,primary,0,3365,4332,NaN,1,2013-07-05 15:41:08-04,2025-09-22 14:10:53-04,17387,NaN
1,0000bd8c-39de-4453-b55d-5e28a9beed38,https://api.nga.gov/iiif/0000bd8c-39de-4453-b5...,https://api.nga.gov/iiif/0000bd8c-39de-4453-b5...,primary,0,3500,4688,NaN,1,2013-08-05 14:31:59-04,2025-09-22 14:10:57-04,19245,NaN
2,0001668a-dd1c-48e8-9267-b6d1697d43c8,https://api.nga.gov/iiif/0001668a-dd1c-48e8-92...,https://api.nga.gov/iiif/0001668a-dd1c-48e8-92...,primary,0,3446,4448,NaN,1,2014-01-02 14:50:50-05,2025-09-22 14:11:18-04,23830,NaN
3,0002e210-8bc2-4471-bb0b-e7bb51d01a40,https://api.nga.gov/iiif/0002e210-8bc2-4471-bb...,https://api.nga.gov/iiif/0002e210-8bc2-4471-bb...,primary,0,2000,1571,900.0,0,2009-12-10 17:28:05-05,2026-01-01 07:14:56.937-05,232817,NaN
4,00032658-8a7a-44e3-8bb8-df8c172f521d,https://api.nga.gov/iiif/00032658-8a7a-44e3-8b...,https://api.nga.gov/iiif/00032658-8a7a-44e3-8b...,primary,0,2674,3798,NaN,1,2010-10-13 15:37:25-04,2026-02-11 09:02:19-05,713,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
130933,fffdeb15-ffd1-4fa7-892f-6883be3b9f3c,https://api.nga.gov/iiif/fffdeb15-ffd1-4fa7-89...,https://api.nga.gov/iiif/fffdeb15-ffd1-4fa7-89...,primary,0,5321,5714,900.0,0,2025-06-05 15:30:56-04,2025-09-22 14:10:43-04,221706,NaN
130934,fffe6d61-e686-478d-bafb-ddae9a48c4de,https://api.nga.gov/iiif/fffe6d61-e686-478d-ba...,https://api.nga.gov/iiif/fffe6d61-e686-478d-ba...,primary,0,4000,1635,NaN,1,2016-05-10 16:23:54-04,2026-01-22 16:32:44-05,169631,NaN
130935,ffff4903-aaf2-4a8f-9f09-60bddc65ddd7,https://api.nga.gov/iiif/ffff4903-aaf2-4a8f-9f...,https://api.nga.gov/iiif/ffff4903-aaf2-4a8f-9f...,primary,0,3403,3405,900.0,0,2011-12-22 15:12:59-05,2026-02-11 18:13:17-05,54273,NaN
130936,ffffc381-9fa3-470d-bfc2-441c643c6039,https://api.nga.gov/iiif/ffffc381-9fa3-470d-bf...,https://api.nga.gov/iiif/ffffc381-9fa3-470d-bf...,primary,0,2861,4000,900.0,0,2016-02-03 20:01:19-05,2026-02-17 17:08:51-05,165884,NaN
130937,ffffdd66-757e-499b-aa2c-c97e1d437da6,https://api.nga.gov/iiif/ffffdd66-757e-499b-aa...,https://api.nga.gov/iiif/ffffdd66-757e-499b-aa...,primary,0,8596,11459,NaN,1,2020-02-11 11:55:29-05,2026-01-21 15:42:11-05,221645,NaN

In [3]:
published_images = published_images[['uuid', 'iiifurl', 'depictstmsobjectid', 'width', 'height']]
objects = objects[['objectid', 'title', 'attribution', 'classification']]

In [4]:
## merging the dataset on basis of object id
merged_df = pd.merge(objects, published_images, left_on='objectid', right_on='depictstmsobjectid', how='inner')
## we will use only paintings (ignoring photograph, portfolio etc..)
merged_df = merged_df[merged_df['classification'] == 'Painting']
merged_df

,objectid,title,attribution,classification,uuid,iiifurl,depictstmsobjectid,width,height
0,0,Saint James Major,Grifo di Tancredi,Painting,7b170a4c-9d44-475c-b294-cee6f43d88af,https://api.nga.gov/iiif/7b170a4c-9d44-475c-b2...,0,2846,5153
1,1,Saint Paul and a Group of Worshippers,Bernardo Daddi,Painting,7bbcfd01-e774-46e7-96d1-a3b03598cd8a,https://api.nga.gov/iiif/7bbcfd01-e774-46e7-96...,1,6004,15544
2,2,Saint Andrew and Saint Benedict with the Archa...,Agnolo Gaddi,Painting,e8a1acb4-f60a-477a-9bfe-61fa5072c514,https://api.nga.gov/iiif/e8a1acb4-f60a-477a-9b...,2,2152,4827
3,3,Madonna and Child Enthroned with Twelve Angels...,Agnolo Gaddi,Painting,abec1c5b-ee32-450d-9398-5c84f1f8cf14,https://api.nga.gov/iiif/abec1c5b-ee32-450d-93...,3,2197,4960
4,4,Saint Bernard and Saint Catherine of Alexandri...,Agnolo Gaddi,Painting,e6890364-4d99-4684-a62b-5060ee3c3446,https://api.nga.gov/iiif/e6890364-4d99-4684-a6...,4,2152,4805
...,...,...,...,...,...,...,...,...,...
126924,231772,The Artist as Lover,Ary de Vois,Painting,10573a7c-1a17-4b95-aa77-c5e4d43a742e,https://api.nga.gov/iiif/10573a7c-1a17-4b95-aa...,231772,7747,9995
126958,232105,"The Red Table: The Skull of Boldini, Marseilles",Joel-Peter Witkin,Painting,5ae09d20-d79b-474d-85f6-7d50651242b1,https://api.nga.gov/iiif/5ae09d20-d79b-474d-85...,232105,12612,9089
126959,232105,"The Red Table: The Skull of Boldini, Marseilles",Joel-Peter Witkin,Painting,8935803d-d798-4427-9184-74f143f472bd,https://api.nga.gov/iiif/8935803d-d798-4427-91...,232105,12891,9457
126960,232107,Untitled (Head of Woman),Henri Le Secq,Painting,4837f246-cbf5-49c2-9dbc-c84066ba3495,https://api.nga.gov/iiif/4837f246-cbf5-49c2-9d...,232107,7638,8553
127100,232343,Wandering Beggars,Salman Toor,Painting,80b44933-3f99-4fac-9540-ade9ba397351,https://api.nga.gov/iiif/80b44933-3f99-4fac-95...,232343,23332,23255

In [5]:
## creating the subset of the dataset
subset_df = merged_df.sample(500)

In [6]:
image_urls = subset_df['iiifurl'].tolist()

In [7]:
import os
import requests
from concurrent.futures import ThreadPoolExecutor

download_dir = "downloaded_images"
os.makedirs(download_dir, exist_ok=True)

def download_image(url):

    image_id = url.split("/")[-1]

    image_url = f"{url}/full/full/0/default.jpg"
    filename = f"{image_id}.jpg"
    filepath = os.path.join(download_dir, filename)

    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        r = requests.get(image_url, headers=headers, stream=True, timeout=20)
        r.raise_for_status()

        with open(filepath, "wb") as f:
            for chunk in r.iter_content(8192):
                if chunk:
                    f.write(chunk)

        print("Downloaded:", filename)

    except Exception as e:
        print("Failed:", image_id, e)


with ThreadPoolExecutor(max_workers=15) as executor:
    executor.map(download_image, image_urls)

Downloaded: 218f46db-6c5c-4bba-b99f-7bd2cd70cefb.jpg
Downloaded: ce14cdf4-fedc-4229-bb08-7f50d89f3871.jpg
Downloaded: 64190215-4741-4d33-a20d-be79ef4202c1.jpg
Downloaded: 31a3cd18-cb80-4b44-abf0-6c84ce152c93.jpg
Downloaded: 44912717-1fcf-4951-b484-ab6cb83b477b.jpg
Downloaded: b65293a3-fb94-431b-8a97-121edabe7dc9.jpg
Downloaded: 45d751c7-7f75-4f27-b269-3976bb95a207.jpg
Downloaded: 9eccee7a-cc2b-4e54-b538-72685c4f4ae7.jpg
Downloaded: 4e237220-1d34-4406-81bb-d390a2075c20.jpg
Downloaded: bb618ae8-92b3-479c-97bd-5c4048993204.jpg
Downloaded: feacc066-4ff8-417c-b2be-f38de838e530.jpg
Downloaded: 40d7c2c9-36f2-47d8-be55-889dc6f4e53c.jpg
Downloaded: ce4a22da-6db1-4f0a-87d5-13b1895b6920.jpg
Downloaded: 889e9c8d-dc78-404c-8725-e9dbe04dd047.jpg
Downloaded: 0c47c30b-6850-49f1-aae2-669f7c1fbb54.jpg
Downloaded: 9990988e-6fc6-4b43-b3ac-11cec2691b54.jpg
Downloaded: 0253c293-4cc1-4131-89a9-f2c997aebba0.jpg
Downloaded: 15a96612-375a-45b7-9918-009409ac79c9.jpg
Downloaded: e61c7940-dd70-4615-8d1b-e776b4ac5ec8.jpg
Downloaded: 47966446-8944-44fa-9166-be2c68bbc30a.jpg
Downloaded: 6d8ac1e9-4de3-448f-851b-7ca0e798e00c.jpg
Downloaded: ffcbf669-7d12-4f64-a3b2-39f9dc3d5a91.jpg
Downloaded: 40067869-f92c-459c-9808-2d3ae3009311.jpg
Downloaded: 10817d7e-7a69-4980-98c4-761b721a38cb.jpg
Downloaded: 27178674-bd03-4754-95fe-2c2406c32b06.jpg
Downloaded: 3be11a31-8053-44fd-8fec-3bf9c57c68a6.jpg
Downloaded: 078614dc-da67-4ef1-a970-51291ed6b4b8.jpg
Downloaded: f297f282-edcc-4190-88ff-96de868ec881.jpg
Downloaded: 81393aa4-26ea-4727-8029-e9ca7081c57b.jpg
Downloaded: 026ad15b-3ac2-4665-b7ff-58c7a32264cc.jpg
Downloaded: d60bdf25-8877-48a8-a9a7-90aff4ccafae.jpg
Downloaded: 2fb51438-c9e4-445a-a0ab-ca44654afbd0.jpg
Downloaded: dce40554-cbe6-4e7d-8dda-533e65544d71.jpg
Downloaded: 0a9e2730-388a-43c6-8713-e61f766e2f92.jpg
Downloaded: e3bef006-65d5-4a30-a070-bb51c76f8b3a.jpg
Downloaded: 83412578-9df5-44f8-9005-2edd8899fda8.jpg
Downloaded: cb2fb43d-7057-4c8b-bcb7-66904ec64319.jpg
Downloaded: 03619368-16a1-4888-a7bb-a6d5520f0fc1.jpg
Downloaded: 457c21c8-0b7e-490d-98ab-7b195da8ed2d.jpg
Downloaded: 2407ccb1-88ba-41d2-9957-739f11fc1dbd.jpg
Downloaded: 82c27626-c929-479b-81de-d8f5c29a1a9f.jpg
Downloaded: 28b9e23a-3c0d-4e93-8349-b1aae8f87aee.jpg
Downloaded: d32bd15e-3b9d-47d1-87d9-b2c509ae7e57.jpg
Downloaded: cb68e531-3638-4cdc-9625-0b3aac32f0d2.jpg
Downloaded: eabc645e-1ee3-49a3-84c9-a9749bad4573.jpg
Downloaded: 0365f216-a97d-4174-bec1-21175b071231.jpg
Downloaded: b27e15a9-a8be-43a4-9ac6-5f5fe9fac97f.jpg
Downloaded: 89a593c9-e4c4-4464-8695-80b22b537340.jpg
Downloaded: 09fc94ea-6ce3-4359-8786-2ddf5121d222.jpg
Downloaded: dbb957df-2395-4f9d-8c96-ea496a608e8d.jpg
Downloaded: 64f98f88-fb97-44a6-8ac1-2c57f4a2f10b.jpg
Downloaded: 3238d41c-6d94-49dc-8b3a-3d069210d022.jpg
Downloaded: e9e472f9-3319-4b9b-804e-0ed4dcb454d6.jpg
Downloaded: 3453f152-eb71-452b-adb7-dead51ff4c3e.jpg
Downloaded: b43e331e-ede9-44ca-a276-0b8806630fbd.jpg
Downloaded: 8110ab38-7330-426b-9b42-2095d08eaf4a.jpg
Downloaded: fc9660b3-e4d3-47d6-bd6d-5a55ba8ad703.jpg
Downloaded: 2937014d-0a8a-4a3c-83e9-6c6f1a4263ee.jpg
Downloaded: 87587715-7af1-4a3b-95db-6d58e4be2037.jpg
Downloaded: 64d419a6-77ee-473b-91c8-374782a31a0f.jpg
Downloaded: d7998c33-be9b-4b5d-b7b2-05b34d8f2528.jpg
Downloaded: 7d161202-0488-4730-ae08-c175a8e85c93.jpg
Downloaded: 823e1490-2c2a-41d6-9189-61c0a302f48f.jpg
Downloaded: cbb9789d-4bc2-446f-8ff9-f7bfe5cdf2c0.jpg
Downloaded: 42dcd09e-4c94-4f3c-be4a-d2b7e4a4bc29.jpg
Downloaded: a7d7601a-e81e-4eb1-bc2c-e3295c0946ca.jpg
Downloaded: 124e9d47-3fb9-422b-a2f9-9492d19f1ef2.jpg
Downloaded: f0b74955-f395-4fd2-b6c3-d85ea7213e58.jpg
Downloaded: bb5e472b-f5e3-47b9-9fc4-cefda61c617f.jpg
Downloaded: 540136ab-88fa-429e-9996-26902dd06662.jpg
Downloaded: 307969c5-6d50-4b3e-af9e-534f42280cee.jpg
Downloaded: f1c10a4e-2de5-4d40-97ba-84723c38a044.jpg
Downloaded: bcf197ac-f4f6-457a-84f0-a59368a7f139.jpg
Downloaded: 98b12bd9-3c1f-4c05-955e-49c69e43fc20.jpg
Downloaded: 65f8a676-7e7a-4b1d-9e38-569fe9c8b29e.jpg
Downloaded: c664a390-2c56-4edc-b070-8f4a84ef5467.jpg
Downloaded: 9ce56bcb-b6de-4030-adb5-a22f00aaeccd.jpg
Downloaded: d277c2a7-190e-475a-bae9-f1cbd0b1218d.jpg
Downloaded: def46860-ab11-44b9-b4f9-21c1428f4ad8.jpg
Downloaded: 793cce4a-0b9c-4c18-96e4-8327c6475eee.jpg
Downloaded: 8913742c-6155-4956-b6b8-2c08d74e220d.jpg
Downloaded: ba1df34a-bb06-4645-81da-017ceb409782.jpg
Downloaded: e5036668-c7e8-497a-9ee5-f27fca34e5aa.jpg
Downloaded: bd5664bc-0ccf-4c93-99c7-188b75b2092d.jpg
Downloaded: c88239a5-a242-43fc-9618-bbabc77721ef.jpg
Downloaded: d4ca2b12-bdf1-4360-a3de-4fb2b1927481.jpg
Downloaded: 3e092add-302a-437c-903f-943373e43e9c.jpg
Downloaded: 98e476f3-8940-4bd6-b2ce-1a335f4f04eb.jpg
Downloaded: a8c5c756-d96b-4788-a9bf-a6cdad569ff4.jpg
Downloaded: e67ba938-318b-46ef-9d9e-607abd6ad5d1.jpg
Downloaded: 0370351f-69b6-4949-ae44-5a11b3cbf7d9.jpg
Downloaded: 5cbb7d21-8c3d-48f4-a728-d71f28ae36b2.jpg
Downloaded: 5b58dbb4-a6f1-4ef7-aff6-afddfa82d181.jpg
Downloaded: 5ae09d20-d79b-474d-85f6-7d50651242b1.jpg
Downloaded: 8928c15c-cf7b-4bdd-9c55-2306f68c7c9b.jpg
Downloaded: dee96945-9b00-487e-9065-f1da4d01dba3.jpg
Downloaded: 1bd606b9-f58c-4d40-8514-f53c63e37dbd.jpg
Downloaded: 31a2c319-1d47-4119-82c1-dbe8f9ed2e58.jpg
Downloaded: 3040e4c8-111b-495c-bae2-a76efd4d8154.jpg
Downloaded: 1f87ebbd-f145-41a3-b6f6-7285e67c96de.jpg
Downloaded: 18480bb2-1e28-4b33-a757-f6e87f677949.jpg
Downloaded: a716d2d8-147d-4a90-b4cb-c7c98750dc95.jpg
Downloaded: aba712d5-686a-4445-858c-669a6c4c4a2b.jpg
Downloaded: f033a552-2901-4c21-95ed-93d13e598632.jpg
Downloaded: 98014fdf-628f-4fa6-8afe-f037471b1be1.jpg
Downloaded: d81bc3eb-69f6-4fdc-be42-e0ed3ef0dae0.jpg
Downloaded: 0fd27212-b70a-4a0b-9e7c-ed0d8bbe7ebf.jpg
Downloaded: 7461a784-1032-41f4-a0b2-8d1e1815facd.jpg
Downloaded: 34ab32a3-8457-4060-acaf-98d1afa79b92.jpg
Downloaded: a5f323a9-6eff-4998-b399-afff8aae3db4.jpg
Downloaded: 3e7328f2-553c-4127-aa0b-034b7f81c46b.jpg
Downloaded: 51bee694-2cc7-4e55-95fa-5a5b972d5359.jpg
Downloaded: 434aafc8-e2d1-4fb9-b367-b7942eb260bc.jpg
Downloaded: 71b3551e-26b5-42dc-9bb8-a8a5f4d989fc.jpg
Downloaded: 6eeecea0-1139-42f7-b009-5b968092b824.jpg
Downloaded: a2d7c971-3f01-47fe-a02a-b4fdd252c28b.jpg
Downloaded: 8fba5e9f-eefe-46be-85f4-14cb8c98e474.jpg
Downloaded: d0273882-086e-437d-b0e0-6898631621f6.jpg
Downloaded: d78be980-42cd-4e9c-badb-e718ba65f0d8.jpg
Downloaded: 4494e5c4-1d38-42fa-9386-ececec527697.jpg
Downloaded: 732faae9-f8fe-459b-b86e-1c6039024179.jpg
Downloaded: dd134103-b436-467a-8b87-32d5a99ba203.jpg
Downloaded: f025fa9f-b4dd-46d0-bf4c-388d82824059.jpg
Downloaded: 2b2c95ba-68bc-4a33-a23e-878bc480e874.jpg
Downloaded: d99afc33-0a0a-49bd-9a7a-9825c4a500bd.jpg
Downloaded: 2871434a-1f57-4a85-86d7-657dbed79953.jpg
Downloaded: f28d9a62-6775-47e1-9d7d-28cc9ecb7fac.jpg
Downloaded: fed0d8c0-6d9d-458e-873a-d74077668d35.jpg
Downloaded: 49cffd8d-5c06-4628-9369-1b6bdb3e7b90.jpg
Downloaded: 972b9157-26fc-4f11-9b9b-ab9c2c253e67.jpg
Downloaded: a820860a-419b-46e4-b474-e0769c96adf3.jpg
Downloaded: 5fb26378-e5e6-4e40-a08a-900d4c5f4564.jpg
Downloaded: c0c1efc0-45c3-4bc0-95bc-3b5c311f13fb.jpg
Downloaded: ad76d21d-1501-459e-a595-573fc76a3c62.jpg
Downloaded: 137e2b12-e15a-463a-8889-2289660f072f.jpg
Downloaded: e4b031d0-6f80-49c6-8fa0-ad6fb3a1d6e2.jpg
Downloaded: 164a9f20-1d2e-49a7-be51-d1140c4dc098.jpg
Downloaded: b770e346-36b9-4093-bcba-2aa5134ec3bb.jpg
Downloaded: 758254df-23a5-4823-8fe5-01f4a132a84b.jpg
Downloaded: 53f8c727-06a1-4fd5-93a2-90d2c3491777.jpg
Downloaded: f28d0f65-c4cd-4101-8a0e-6690bbbd3996.jpg
Downloaded: 719a2b8f-5b98-4c0b-9319-5d3908e720bf.jpg
Downloaded: 5075f033-a2f6-41c0-8e9a-db25dbcc48da.jpg
Downloaded: 64ab9db6-15c8-4558-bbef-bf9388e8a3a3.jpg
Downloaded: cab68476-336a-4223-90fe-eb33ba2e5293.jpg
Downloaded: f7900072-fa44-4f8f-bbc2-b8d0cbcc09ad.jpg
Downloaded: 350ae4bb-a288-4d65-be2a-0680e75ff6d6.jpg
Downloaded: 4d3cccf0-ae12-46ba-83a0-11c941cf520e.jpg
Downloaded: ec91a058-14aa-47ca-810d-9f31b3006062.jpg
Downloaded: 3a5decbc-9cce-4804-93c1-7c29806d8f55.jpg
Downloaded: 180769c9-d4bc-4756-951c-c384651be9ac.jpg
Downloaded: 199583e2-2fe5-428b-a44b-0ef2bfe459e6.jpg
Downloaded: 7349411e-b7c9-4739-95c9-bd541af9aca6.jpg
Downloaded: f9b02d1b-69f0-4aa7-a798-c2948cf17b7c.jpg
Downloaded: c1f8fcf4-7826-4e51-bbb7-57e511757cad.jpg
Downloaded: d08855df-fa26-41ff-ab62-6f5def210926.jpg
Downloaded: a755f55b-5e02-4417-980d-e7bd170e5eef.jpg
Downloaded: 4196f97b-1edb-4fae-aa9f-882afe35978b.jpg
Downloaded: 565e5754-84c4-4d60-9cf3-00bfdad91fa0.jpg
Downloaded: f653625c-5432-44df-82da-65a966d350db.jpg
Downloaded: e55d5a64-1d05-4b3c-ae70-152de986652d.jpg
Downloaded: 50a2866d-de51-4824-a6b6-6c8643d94335.jpg
Downloaded: d50b902a-e81d-44b8-9f6e-e525585cc5f2.jpg
Downloaded: 191b9190-943a-425d-9890-f569e38672e0.jpg
Downloaded: 8edeacf2-a972-487a-a2b0-94a20724e319.jpg
Downloaded: eb5ad869-b1c7-4cb1-9658-348751d9a0e9.jpg
Downloaded: db30ea5b-a94a-4cb2-bc67-79a2343554bf.jpg
Downloaded: 329a6399-ba55-4f39-9f9c-7e12a28dd084.jpg
Downloaded: 15ca024f-258c-4b46-a1c8-f30c008318e1.jpg
Downloaded: a82d6878-e9c4-4728-a234-ea0191463570.jpg
Downloaded: 60b18ca5-805e-42a7-92a9-4b37da87ef65.jpg
Downloaded: 0cb39282-deb4-4a43-97c5-e681be9b5d6f.jpg
Downloaded: eaa4615c-fa8f-4fc5-b207-0866402c872e.jpg
Downloaded: 2b9b82ee-eb14-4b71-a6e5-4506b776ec22.jpg
Downloaded: f44a5f2b-333b-4b51-9b46-bad26a22b474.jpg
Downloaded: 145d5c3f-945c-4d98-b281-24fd1015d2cd.jpg
Downloaded: b74be188-7a6a-4fc8-866e-55c4e11937c9.jpg
Downloaded: 12aab9ab-9927-40a5-b2fe-9737d1a37f05.jpg
Downloaded: 5174ca9a-42e7-4420-b5e5-ad063a9092f6.jpg
Downloaded: ca6bdfda-1f11-4dfa-bb1a-52c124281595.jpg
Downloaded: 302a176e-21d2-4c7c-b90b-d3d72f457211.jpg
Downloaded: e36deb2f-c228-4b03-b503-c62153f39829.jpg
Downloaded: dcd26a0e-c76a-4a81-896c-1798465ecf80.jpg
Downloaded: 7d846603-308b-4db8-89bd-6e21a3367a39.jpg
Downloaded: 89f3a6fb-5b1d-4bca-8508-90c6444cd8ea.jpg
Downloaded: aa76715a-a53c-411f-878a-5e5680931baf.jpg
Downloaded: 7ff8e174-13ba-4ea4-a70f-e43e34c74570.jpg
Downloaded: 82c4f800-4a50-468a-b596-419a86a280b1.jpg
Downloaded: 593474fc-625a-4b42-84eb-ecfaca933853.jpg
Downloaded: dfc4c484-5e6d-46eb-baf7-54276e6d9077.jpg
Downloaded: f64d6b4a-c327-498a-ada4-bc3ef21228ff.jpg
Downloaded: 3e41adb7-54e3-4011-a9c3-e86482fc3405.jpg
Downloaded: 19df67b7-a80f-48fb-9c10-42d5990c4fbf.jpg
Downloaded: 9ceaf1ac-8e2a-4a26-8d4c-44c5d40bcefd.jpg
Downloaded: 56303f18-6101-4d5d-9b03-20b58d657afa.jpg
Downloaded: 596a5fa1-b737-4725-bb67-bb0baddd95a1.jpg
Downloaded: a780f9ed-0da2-4f2a-85fb-e8a6ec1a4ff7.jpg
Downloaded: d15293c8-60a7-438e-b262-6f4521501494.jpg
Downloaded: 49f2a9e6-4aed-4ab5-98ce-993a0a6de58b.jpg
Downloaded: cdef8773-6058-4a73-aee0-6eacce555bbd.jpg
Downloaded: 5aabd016-748d-4f81-855d-7963dc5a62b4.jpg
Downloaded: 811c5eae-cf56-43a0-978b-faa1c59e0c08.jpg
Downloaded: a40be973-8479-4dd8-a4b8-f878924ebf78.jpg
Downloaded: 71e09ac6-9143-49fe-b25b-bb4bf5b56dfc.jpg
Downloaded: e09f2884-f3ed-4275-a572-ea5a35769030.jpg
Downloaded: 229f4d1c-b36d-4845-b2c0-a4c092520ea2.jpg
Downloaded: dca8cb71-8556-4a36-8e81-58a721b94177.jpg
Downloaded: d6bb6423-9d08-4f22-bf1d-8102b61fefde.jpg
Downloaded: c95ed4b0-2044-40ca-97c3-27f75ac822b1.jpg
Downloaded: 28847b06-0eb8-406e-befc-5867fd9651c2.jpg
Downloaded: 5e75e5d2-0a63-45d5-89f4-80b788682ed3.jpg
Downloaded: f3273de9-2983-475e-bf18-92793c499f50.jpg
Downloaded: b347da91-8047-457f-8a44-949318dee128.jpg
Downloaded: 3b4deb5c-7c1c-4d67-bc5f-56bbde0a1bed.jpg
Downloaded: 8a8230d6-310c-4a2f-98d9-143289d09449.jpg
Downloaded: d32bae92-8e05-4166-adcb-c7b93fb49c99.jpg
Downloaded: 74649672-812b-4c22-84a4-a0e36695dfe2.jpg
Downloaded: 568d1621-5f36-4611-8035-237bb9ac178c.jpg
Downloaded: f3963d74-6a06-4763-b2f1-dcfcd801a5f8.jpg
Downloaded: cfa0016f-41bd-4e16-a94e-a7e349652ff0.jpg
Downloaded: 49807e69-03b9-4d9e-b168-022317dfa8cc.jpg
Downloaded: d8d0df0b-2006-41f0-b111-b3981ac66be5.jpg
Downloaded: d0840afa-9aaf-49c0-8e2f-b3dff652bf2d.jpg
Downloaded: 05e6ca89-e950-4ff7-8463-50f553ce2ad6.jpg
Downloaded: de5e64f1-9e54-4927-8127-0da63e849f06.jpg
Downloaded: 4a9d80ee-0d43-4b24-8bc7-cc60ff6691bd.jpg
Downloaded: b6e9cf0e-fa83-4507-8f96-4199e3d85af5.jpg
Downloaded: 8643c5d9-6532-4e84-aab8-e9952465a8a8.jpg
Downloaded: 57e86e75-8d4a-41bd-834a-af4352d1b00b.jpg
Downloaded: 299ddaef-0a69-4a23-96dc-71d7f1ee6112.jpg
Downloaded: a591fe60-9ef8-49ed-8d09-91dd77ea0fa6.jpg
Downloaded: 56561c9f-5aad-45e5-9381-651ee5f350f1.jpg
Downloaded: f2fc7310-79cc-4ece-98f5-051349034b9e.jpg
Downloaded: 7d903b68-1435-4b80-ab8d-5f8b95b433c8.jpg
Downloaded: 0072e45c-c9ef-48ac-b4dd-b5994cf5546c.jpg
Downloaded: 9b65e8fc-64e8-429f-948a-4073d5f5478f.jpg
Downloaded: 53d4f9d0-0c6c-4e01-a858-733f9a6ed60e.jpg
Downloaded: c25b29e5-f86a-442c-a544-5c89c767b48b.jpg
Downloaded: ce2428ad-dd31-4049-8f9a-d63ae483070e.jpg
Downloaded: a7858589-5528-4273-bb1a-638c6a3caca7.jpg
Downloaded: 810dcb50-63ff-4233-8e42-bfd7508d68e9.jpg
Downloaded: ed2ea547-9cc6-437f-9068-af7f4a916c9d.jpg
Downloaded: 612bcf29-8edd-4046-9e20-e1d5db3ce619.jpg
Downloaded: d98a958b-291a-40f3-9dda-b5d371b69dd7.jpg
Downloaded: 33e69f85-6eec-4d80-8ddd-48fde0795bef.jpg
Downloaded: e48ca0e5-aa7c-4ab8-85dc-34221a5544f7.jpg
Downloaded: 8d19b986-0955-4ff6-af8c-b105a873d82b.jpg
Downloaded: aa829214-99b1-4978-8ef7-75bd6d790e2c.jpg
Downloaded: acf6fb2a-7774-49a5-9b9b-05740a8191fe.jpg
Downloaded: a46e6f59-4fab-4795-8cad-1999b37c52ae.jpg
Downloaded: da63faa0-8a73-40cb-99ca-adc47ee0df82.jpg
Downloaded: d3b87c14-c6ac-4812-bafb-a9b2348cbbec.jpg
Downloaded: 9f8372e2-ba83-4d8f-83d2-8d371768ad32.jpg
Downloaded: d345149c-3d2d-4ffa-84ce-1c9f788244fc.jpg
Downloaded: 3a948539-d3c8-4be3-b055-c23f97ed018f.jpg
Downloaded: 92fe5a54-69f8-4525-a93d-3553daad3890.jpg
Downloaded: ef2b7b7d-966d-4405-a2ed-adb63409b32c.jpg
Downloaded: a28d894d-f040-4442-bd67-867b601d5099.jpg
Downloaded: 8c36f19a-c3c2-450f-b6b7-5217d1eafc82.jpg
Downloaded: ce8a7a7f-14f1-4780-ba00-20421e130b2f.jpg
Downloaded: 763baae6-c40c-40c1-b09e-627ee5084317.jpg
Downloaded: 434ba932-0cb3-49b0-a32c-117193873932.jpg
Downloaded: 7a640b23-8b59-4235-b27c-3e17d7064c05.jpg
Downloaded: c5f5cfa6-6150-435a-bf5d-a0a7a55c52f7.jpg
Downloaded: f8a0c85d-7cfa-4e63-aeea-d67f99ea9a28.jpg
Downloaded: b2addf3c-af57-4aa6-939d-02dadefb82cb.jpg
Downloaded: 380d0db5-1a74-4820-bc80-f75d7b6fe2fe.jpg
Downloaded: f578ab60-df7d-496b-b223-53bfedf1348d.jpg
Downloaded: d15b57c6-ff87-459e-ab0f-ab9d80cbf35a.jpg
Downloaded: 77f01fa0-9125-42e7-a5d0-71f2a1e57888.jpg
Downloaded: 760c3fe8-9a0e-4c35-ac9d-23bb294a0058.jpg
Downloaded: 62fcd56d-e6c1-4c5b-9353-38d50a2629b4.jpg
Downloaded: dec22590-2c27-44e7-8a1a-e79a2e2b6e34.jpg
Downloaded: 20eb9317-4237-419b-91e8-3c5a568fc812.jpg
Downloaded: 8c978c3f-88f0-447a-a36c-6848baf9514a.jpg
Downloaded: 7c294838-67c3-455e-9d7c-3bdde49d6328.jpg
Downloaded: b39f3e67-7044-4964-98a3-0d0a1c107eee.jpg
Downloaded: a74f2aea-2c0f-4215-a8b1-894a8cb3997a.jpg
Downloaded: adb17083-dc09-4c12-a94e-6fdb938ef9a6.jpg
Downloaded: 6b9afa63-72ca-4160-8b92-38b8372d4544.jpg
Downloaded: ae3ad660-da09-41dd-94e8-75be91176deb.jpg
Downloaded: b5e7d09d-c607-483b-8db0-331431386196.jpg
Downloaded: 2b3b85d3-07ba-4368-9354-6b8a01b1f263.jpg
Downloaded: 710465b7-d449-4eee-b035-76519b24c0cb.jpg
Downloaded: 1bc7b8e3-2829-4c5a-8679-cddf5d7bff19.jpg
Downloaded: ac936d8c-9ae1-491f-8848-421016c51c9b.jpg
Downloaded: bad46dd7-bc30-4517-8a0d-51ed7e867c3b.jpg
Downloaded: 676fa96e-ad4e-4209-b985-ae0c15f5d902.jpg
Downloaded: 387cfa89-76c2-4347-a0e1-631c7b263691.jpg
Downloaded: 255840fd-ecfe-472f-93eb-350781ac9671.jpg
Downloaded: 357b1f5b-2d1b-4bb1-8246-02e38b08476a.jpg
Downloaded: 2eea6d86-1364-44ee-a4fe-cbada9e33087.jpg
Downloaded: 061cc5a5-8586-434a-bdc0-bb65e584568f.jpg
Downloaded: ce9bbbbe-adc3-4cde-94e1-7c74a61e95e5.jpg
Downloaded: e672d55c-3798-45b3-9561-c6976d131f45.jpg
Downloaded: a5c51660-b530-44e4-9a7c-96c8a496d0e3.jpg
Downloaded: 45a13383-5e77-4111-bc04-5e579bbb5dd0.jpg
Downloaded: 3f2e5dae-30af-442a-baa4-4541853b756b.jpg
Downloaded: 54ec9dca-a111-4734-9249-521b59a0dfaa.jpg
Downloaded: f1d3f3fa-49c4-4f82-8473-9831bbdad475.jpg
Downloaded: c473f61b-acf3-4103-ab4e-3beae5d48ced.jpg
Downloaded: 4a8a90c9-d3f7-498e-9cad-3b66f403a693.jpg
Downloaded: dbcb1da7-a92d-4104-bbac-419f8cccde88.jpg
Downloaded: 8c1751e5-935b-41e6-ba17-c15bb8bbe8f3.jpg
Downloaded: a2270c17-dd31-4ac4-9d83-a97dcbabaa4b.jpg
Downloaded: 973f15d7-f2ab-4002-af7a-19fdd269453c.jpg
Downloaded: 2c475c62-639d-4e1f-b5ef-62671c4f2a32.jpg
Downloaded: b9c9e75c-e81b-4dab-aafe-12045660422f.jpg
Downloaded: 8ff2d6a0-c863-4127-bb9a-7edd6a56650a.jpg
Downloaded: f2e8f414-5b22-4667-92eb-8ac452a50da9.jpg
Downloaded: 0d13ec9b-daac-4768-8a3c-e7c79ded3a30.jpg
Downloaded: 5044a30b-b86e-4c12-9178-7aedaadb36e6.jpg
Downloaded: 0b253b19-3f10-4116-8ce6-5b43ba041b65.jpg
Downloaded: 48b6e029-9d34-4ed3-957e-36e4252d34d2.jpg
Downloaded: 9516feae-fcd3-44ff-9e93-fc9fa39ad063.jpg
Downloaded: f358a660-2fdf-43a2-bdde-621dc7a86d59.jpg
Downloaded: 13371c7c-eec7-4f29-be22-c0e0f63b5ffa.jpg
Downloaded: f6147ee0-6487-460d-8574-fd170d203a74.jpg
Downloaded: 592478a1-a524-4b37-a58e-241a790fe04c.jpg
Downloaded: ef245fcb-29f8-45c8-b58c-b960f83320af.jpg
Downloaded: d56ff173-a09e-469d-871e-d0a7bd346e65.jpg
Downloaded: 14ab81bb-072d-405f-a397-7b7a850d67c9.jpg
Downloaded: f01e235b-47e6-42b3-b10f-9f131ac32637.jpg
Downloaded: 9aeed8f9-50ef-43b0-b006-feaa192fd878.jpg
Downloaded: b5a25512-bc7d-449c-ba5b-fd091ae27ec0.jpg
Downloaded: 48dcb14c-b765-4f38-93f1-158085e89829.jpg
Downloaded: c215e277-6a1a-4b25-8d0a-2bfa4db13d6a.jpg
Downloaded: 2e508778-4471-43ab-82b1-0e1aa0cd4b63.jpg
Downloaded: 87ece172-f4cb-4a1c-9439-3f29ef085665.jpg
Downloaded: d43ebcc3-27cd-4150-99af-fa84629779ab.jpg
Downloaded: bdcebf64-a20f-43ce-bdcf-af890e5bc907.jpg
Downloaded: 8c5a2781-b0a2-47b4-953b-e568ca1c7999.jpg
Downloaded: ee686635-b527-4e36-82fc-53f09e10cee4.jpg
Downloaded: 145885c8-a3eb-4599-b86c-7b1aeaa4596f.jpg
Downloaded: 6f169290-6717-4c01-9767-2f675230718d.jpg
Downloaded: 7408044a-5130-49b9-bf8e-5ef5133bad98.jpg
Downloaded: fe83efd1-e3a7-44a1-9daa-3aefcad374f6.jpg
Downloaded: c04a122a-ebdf-4f1a-b809-347f170bb356.jpg
Downloaded: b8cbb100-dee4-45de-b225-20dd379b5619.jpg
Downloaded: 03cea09d-adc8-4241-8938-057842d7375f.jpg
Downloaded: 50ae285a-ecb6-4125-a094-019cfd9127c3.jpg
Downloaded: bfc54c5f-a5ea-4aca-9e8e-e2ff169c48b5.jpg
Downloaded: fc7ddec0-daba-4514-afac-0080823fab75.jpg
Downloaded: 2430a030-7bcd-4433-a59e-91cfc9ead186.jpg
Downloaded: 3676623a-96ad-4365-810e-d14bcb6fd698.jpg
Downloaded: cec223de-bf79-46d6-acb0-73fb36c34920.jpg
Downloaded: e6d01922-9b22-4615-a239-86a528c0608d.jpg
Downloaded: 3ba8ddc1-4c33-4b79-a3b9-e999b1d9b6f7.jpg
Downloaded: 0ee4ce32-e06d-463a-9c37-a1390168525e.jpg
Downloaded: 974113d9-ccb8-490a-8ef0-66e77db76948.jpg
Downloaded: ae346dd2-83be-4ce0-81e3-976212c33ce3.jpg
Downloaded: 0dff6c29-1e00-45cb-90ba-49a8ef600e15.jpg
Downloaded: 80fffb38-6661-4c39-9825-a87703fe86cd.jpg
Downloaded: b168f365-b640-43f0-a6b3-7cf067e6ed2d.jpg
Downloaded: 3b398f2e-ba99-4455-b55f-824e39f849f5.jpg
Downloaded: 7daf04f0-9841-4add-9d37-22df084f5ea2.jpg
Downloaded: 9c0e94a1-09ed-47fd-ad50-8a364d45f3e1.jpg
Downloaded: 336d6784-a562-4bec-9a1e-bbc61054fd49.jpg
Downloaded: ca1dc4dd-6697-46c1-9fe5-95cd21b2a71f.jpg
Downloaded: 68c51b2f-ecd7-4f6e-ada5-a066ba07565c.jpg
Downloaded: 4dd0739b-4dbc-4a6a-acf6-3f8e6e4fcaf3.jpg
Downloaded: 8f492ff3-8a7d-455f-bfbc-538684d9128b.jpg
Downloaded: 8681c69a-8b23-453d-a7f6-de663a2253d6.jpg
Downloaded: 8f2ef029-1356-43a5-b34c-9522ffb058ec.jpg
Downloaded: 17cb936f-4fe7-429d-ad14-d9c003da5bef.jpg
Downloaded: 88537502-0c26-4371-bca4-26f96ca8c845.jpg
Downloaded: eb826b10-2c85-44b2-85f8-eba45d5a3226.jpg
Downloaded: b3d16da2-8fc4-4961-a319-f3ae28a609bd.jpg
Downloaded: b565a60f-1432-48c7-8ae8-009497cdbe09.jpg
Downloaded: 85d40b25-aef8-4586-829e-1b1d51203ff7.jpg
Downloaded: 835f5eee-6399-43d8-8bfc-dcaf2a3effd8.jpg
Downloaded: 25bc9965-9bb0-496f-a4e6-b89160382df3.jpg
Downloaded: 4f24b68a-e110-4537-9dbc-59f1bece8af2.jpg
Downloaded: 58275103-1fa9-4058-8921-34f8e8777041.jpg
Downloaded: 160418dd-3a76-4a49-9240-f9570931f7e5.jpg
Downloaded: 7fb87016-166b-4de4-ad72-bff6ac73ed25.jpg
Downloaded: baa196ea-c6c8-4fcc-b320-5ebb2f49c8cb.jpg

Now, i've downloaded the images from the url locally, and added the local path in the dataset

In [8]:
import shutil

shutil.move("/content/downloaded_images", "/content/drive/MyDrive/Colab Notebooks/ArtExtract/downloaded_images")

'/content/drive/MyDrive/Colab Notebooks/ArtExtract/downloaded_images'

In [9]:
subset_df["image_path"] = subset_df["uuid"].apply(lambda x: f"downloaded_images/{x}.jpg")

In [10]:
## keeping only the required useful columns
subset_df = subset_df[['uuid', 'title', 'attribution', 'classification', 'image_path']]

### Tell them what i would've done if the dataset was huge (chromaDB, Qdrant etc...)

### what i've also seen as options were : siamese networks
### I'll use the rest data from the dataset to cross-check whether my model really performed (or found out similar titled or described images ??)

In [11]:
subset_df.to_csv('/content/drive/MyDrive/Colab Notebooks/ArtExtract/task2_df.csv', index=False)

In [12]:
## final dataset
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ArtExtract/task2_df.csv')

In [13]:
dataset

,uuid,title,attribution,classification,image_path
0,4e237220-1d34-4406-81bb-d390a2075c20,Muro Romano,Mimmo Rotella,Painting,downloaded_images/4e237220-1d34-4406-81bb-d390...
1,ce14cdf4-fedc-4229-bb08-7f50d89f3871,Scene from Ancient History,Giovanni Battista Tiepolo,Painting,downloaded_images/ce14cdf4-fedc-4229-bb08-7f50...
2,40d7c2c9-36f2-47d8-be55-889dc6f4e53c,Nude Seated,Childe Hassam,Painting,downloaded_images/40d7c2c9-36f2-47d8-be55-889d...
3,9eccee7a-cc2b-4e54-b538-72685c4f4ae7,Sir John Dick,Gilbert Stuart,Painting,downloaded_images/9eccee7a-cc2b-4e54-b538-7268...
4,6d8ac1e9-4de3-448f-851b-7ca0e798e00c,Still Life with Ham,Gerret Willemsz Heda,Painting,downloaded_images/6d8ac1e9-4de3-448f-851b-7ca0...
...,...,...,...,...,...
495,f2c94c3b-d970-4675-bab9-1bb4b60ac02a,"Georgiana, Shirley, and Sharon",Nancy Shaver,Painting,downloaded_images/f2c94c3b-d970-4675-bab9-1bb4...
496,e5783ee7-1f28-4a83-95ad-e7907a34202e,The Shipwreck,Claude-Joseph Vernet,Painting,downloaded_images/e5783ee7-1f28-4a83-95ad-e790...
497,194c86fb-0bcc-47eb-b848-f4bf2f24c30e,Horsemen and Herdsmen with Cattle,Aelbert Cuyp,Painting,downloaded_images/194c86fb-0bcc-47eb-b848-f4bf...
498,e0a38a65-5b7d-4146-b734-b256b0e0331d,Agrippina and Germanicus,Sir Peter Paul Rubens,Painting,downloaded_images/e0a38a65-5b7d-4146-b734-b256...
499,836ad70d-2814-4be2-9874-6da050d3f0ae,Andrea de' Franceschi,after Titian,Painting,downloaded_images/836ad70d-2814-4be2-9874-6da0...